export const data1=[
    {
        id:1,
        img:require('../images/cat-1.jpg'),
        type:"commercial",
        listing:"90"
    }
    ,{
        id:2,
        img:require('../images/cat-2.jpg'),
        type:"Residential",
        listing:"117"
    }
    ,{
        id:3,
        img:require('../images/cat-3.jpg'),
        type:"Villas",
        listing:"90"
    },
    {
        id:4,
        img:require('../images/cat-4.jpg'),
        type:"Apartment",
        listing:"10"
    }
    ,{
        id:5,
        img:require('../images/cat-5.jpg'),
        type:"Beach House",
        listing:"90"
    }
    ,{
        id:6,
        img:require('../images/cat-6.png'),
        type:"Duplex",
        listing:"9"
    }

]